##replace the lines with the "$"
services:
  app:
    image: idkspanish/dbdemo
    container_name: app
    ports:
      - "5000:8080"
    depends_on:
        - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${Db_Name}
      - DB_USER=${Db_User}
      - DB_PASS=${Db_Pass}

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=${Db_User}
      - POSTGRES_PASSWORD=${Db_Pass}
      - POSTGRES_DB=${Db_Name}
    ports:
      - "5433:5432"